service: blog-emailer

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  sendEmail:
    handler: handler.sendEmail
    environment:
      FROM: '"Blog Email" <justindanielfuller+blogemail@gmail.com>'
      SERVICE: gmail
      SUBJECT: Email From Blog
      TEXT: There was no email content.
    