service: medium-blog-posts

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  posts:
    handler: handler.posts
    events:
      - http:
          path: posts
          method: get
          cors: true
