// flow-typed signature: 9e57e6350b61b8b9cb3f14c249f953cc
// flow-typed version: <<STUB>>/compose-promise_v^1.0.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compose-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'compose-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'compose-promise/index' {
  declare module.exports: $Exports<'compose-promise'>;
}
declare module 'compose-promise/index.js' {
  declare module.exports: $Exports<'compose-promise'>;
}
