// flow-typed signature: 5a85847dac957c8c23f74f49d3df79f2
// flow-typed version: <<STUB>>/promise-compose_v^1.1.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise-compose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise-compose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'promise-compose/index' {
  declare module.exports: $Exports<'promise-compose'>;
}
declare module 'promise-compose/index.js' {
  declare module.exports: $Exports<'promise-compose'>;
}
