// flow-typed signature: dbba60ef914e49487e733b309570c6bf
// flow-typed version: <<STUB>>/react-native-admob_v^1.2.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-admob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-admob' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-admob/RNAdMobBanner' {
  declare module.exports: any;
}

declare module 'react-native-admob/RNAdMobInterstitial' {
  declare module.exports: any;
}

declare module 'react-native-admob/RNAdMobRewarded' {
  declare module.exports: any;
}

declare module 'react-native-admob/RNPublisherBanner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-admob/index' {
  declare module.exports: $Exports<'react-native-admob'>;
}
declare module 'react-native-admob/index.js' {
  declare module.exports: $Exports<'react-native-admob'>;
}
declare module 'react-native-admob/RNAdMobBanner.js' {
  declare module.exports: $Exports<'react-native-admob/RNAdMobBanner'>;
}
declare module 'react-native-admob/RNAdMobInterstitial.js' {
  declare module.exports: $Exports<'react-native-admob/RNAdMobInterstitial'>;
}
declare module 'react-native-admob/RNAdMobRewarded.js' {
  declare module.exports: $Exports<'react-native-admob/RNAdMobRewarded'>;
}
declare module 'react-native-admob/RNPublisherBanner.js' {
  declare module.exports: $Exports<'react-native-admob/RNPublisherBanner'>;
}
