service: portfolio

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  posts:
    handler: index.posts
    events:
      - http:
          path: posts
          method: get
          cors: true
  sendEmail:
    handler: index.sendEmail
    environment:
      FROM: '"Blog Email" <justindanielfuller+blogemail@gmail.com>'
      SERVICE: gmail
      SUBJECT: Email From Blog
      TEXT: There was no email content.
